var config = {
    configName: "dev",
    address: "localhost",
    port: 8080,
    ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses

    electronOptions: {
        disableAutoHideCursor: true,
        resizable: true,
        movable: true,
        closable: true,
        fullscreen: false,
        width: 900,
        height: 600,
    },
    language: "en",
    timeFormat: 24,
    units: "metric",

    modules: [
        {
            module: "alert",
        },
        {
            module: "updatenotification",
            position: "top_bar",
        },
        {
            module: "clock",
            position: "top_left",
            config: {
                timeFormat: 12,
                showPeriodUpper: true,
            },
        },

        {
            module: "calendar",
            position: "top_left",
            header: "Schedule",

            config: {
                calendars: [
                    {
                        maximumNumberOfDays: 20,
                        broadcastPastEvents: true,
                        symbol: "calendar",
                        url: "https://calendar.google.com/calendar/ical/anthony%40fyresite.com/public/basic.ics",
                    },
                ],
            },
        },

        {
            module: "currentweather",
            position: "top_right",
            config: {
                location: "Eden Prairie",
                locationID: "5025219", //ID from http://www.openweathermap.org/help/city_list.txt
                appid: "6025ad4ccd664fe7465bad079e82058b",
                units: "imperial",
                timeFormat: 12,
            },
        },
        {
            module: "weatherforecast",
            position: "top_right",
            header: "Weather Forecast",
            config: {
                location: "Eden Prairie",
                locationID: "5025219", //ID from http://www.openweathermap.org/help/city_list.txt
                appid: "6025ad4ccd664fe7465bad079e82058b",
                units: "imperial",
            },
        },
        // {
        //     module: "newsfeed",
        //     position: "bottom_bar",
        //     config: {
        //         feeds: [
        //             {
        //                 title: "New York Times",
        //                 url: "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml",
        //             },
        //             {
        //                 title: "BBC",
        //                 url: "http://feeds.bbci.co.uk/news/rss.xml?edition=uk",
        //             },
        //             {
        //                 title: "The Wall Street Journal",
        //                 url: "https://www.wsj.com/xml/rss/3_7085.xml",
        //             },
        //             {
        //                 title: "The Washington Post",
        //                 url: "http://feeds.washingtonpost.com/rss/national",
        //             },
        //             {
        //                 title: "The Economist",
        //                 url: "http://www.economist.com/sections/united-states/rss.xml",
        //             },
        //             {
        //                 title: "The New Yorker",
        //                 url: "https://www.newyorker.com/feed/everything",
        //             },
        //             {
        //                 title: "Star Tribune",
        //                 url: "http://www.startribune.com/local/index.rss2",
        //             },
        //             {
        //                 title: "USA Today",
        //                 url: "http://rssfeeds.usatoday.com/usatoday-NewsTopStories",
        //             },
        //             {
        //                 title: "TIME Magazine",
        //                 url: "http://feeds2.feedburner.com/time/topstories",
        //             },
        //             {
        //                 title: "The Guardian",
        //                 url: "https://www.theguardian.com/world/rss",
        //             },
        //             {
        //                 title: "The Times",
        //                 url: "http://rss.nytimes.com/services/xml/rss/nyt/World.xml",
        //             },
        //         ],
        //         showSourceTitle: true,
        //         showPublishDate: true,
        //         showDescription: true,
        //     },
        // },

        {
            module: "MMM-GoogleMapsTraffic",
            position: "top_left",
            config: {
                key: "AIzaSyB8Q_NCR9A2bnpWkYfiVWE2oMXlVvgSiF4",
                mapTypeId: "roadmap",
                lat: 33.6050991,
                lng: -112.4052392,
                height: "300px",
                width: "350px",
                styledMapType: "standard",
                disableDefaultUI: true,
                backgroundColor: "hsla(0, 0%, 0%, 0)",
                markers: [
                    {
                        lat: 33.6050991,
                        lng: -112.4052392,
                        fillColor: "#9966ff",
                    },
                ],
            },
        },

        {
            module: "MMM-Traffic",
            position: "top_left",
            classes: "dimmed medium", //optional, default is "bright medium", only applies to commute info not route_name
            config: {
                api_key: "AIzaSyB8Q_NCR9A2bnpWkYfiVWE2oMXlVvgSiF4",
                travelMode: "DRIVING",
                origin: "223 S Rush Cir E, Chandler, AZ 85226",
                destination: "1201 E Jefferson St #6, Phoenix, AZ 85034",
                mon_destination: "1201 E Jefferson St #6, Phoenix, AZ 85034",
                fri_destination: "1201 E Jefferson St #6, Phoenix, AZ 85034",
                route_name: "Home to Work",
                changeColor: true,
                showGreen: true,
                limitYellow: 5, // Greater than 5% of journey time due to traffic
                limitRed: 20, // Greater than 20% of journey time due to traffic
                traffic_model: "pessimistic",
                interval: 120000, // 2 minutes
                allTime: true,
                showWeekend: true,
            },
        },

        {
            module: "MMM-MyScoreboard",
            position: "top_right",
            classes: "default everyone",
            header: "My Scoreboard",
            config: {
                showLeagueSeparators: true,
                colored: true,
                viewStyle: "mediumLogos",
                sports: [
                    {
                        league: "NHL",
                        groups: ["Atlantic"],
                    },
                    {
                        league: "NBA",
                        teams: ["TOR"],
                        groups: ["Pacific", "Central"],
                    },
                    {
                        league: "MLB",
                        teams: ["TOR", "CHW", "NYY"],
                    },
                    {
                        league: "NFL",
                        teams: ["BUF", "NYJ", "NYG"],
                    },
                    {
                        league: "CFL",
                        teams: [
                            "AFA",
                            "AKR",
                            "ALA",
                            "APP",
                            "ARIZ",
                            "ARK",
                            "ARMY",
                            "ARST",
                            "ASU",
                            "AUB",
                            "BALL",
                            "BAY",
                            "BC",
                            "BGSU",
                            "BSU",
                            "BUFF",
                            "BYU",
                            "CAL",
                            "CCU",
                            "CHAR",
                            "CIN",
                            "CLEM",
                            "CMU",
                            "COLO",
                            "CONN",
                            "CSU",
                            "DUKE",
                            "ECU",
                            "EMU",
                            "FAU",
                            "FIU",
                            "FLA",
                            "FRES",
                            "FSU",
                            "GASO",
                            "GAST",
                            "GT",
                            "HAW",
                            "HOU",
                            "IDHO",
                            "ILL",
                            "IND",
                            "IOWA",
                            "ISU",
                            "KENT",
                            "KSU",
                            "KU",
                            "LOU",
                            "LSU",
                            "LT",
                            "M-OH",
                            "MD",
                            "MEM",
                            "MIAMI",
                            "MICH",
                            "MINN",
                            "MISS",
                            "MIZ",
                            "MRSH",
                            "MSST",
                            "MSU",
                            "MTSU",
                            "NAVY",
                            "NCST",
                            "ND",
                            "NEB",
                            "NEV",
                            "NIU",
                            "NMSU",
                            "NW",
                            "ODU",
                            "OHIO",
                            "OKLA",
                            "OKST",
                            "ORE",
                            "ORST",
                            "OSU",
                            "PITT",
                            "PSU",
                            "PUR",
                            "RICE",
                            "RUTG",
                            "SC",
                            "SDSU",
                            "SJSU",
                            "SMU",
                            "STAN",
                            "SYR",
                            "TA&M",
                            "TCU",
                            "TEM",
                            "TENN",
                            "TEX",
                            "TLSA",
                            "TOL",
                            "TROY",
                            "TTU",
                            "TULN",
                            "TXST",
                            "UAB",
                            "UCF",
                            "UCLA",
                            "UGA",
                            "UK",
                            "ULL",
                            "ULM",
                            "UMASS",
                            "UNC",
                            "UNLV",
                            "UNM",
                            "UNT",
                            "USA",
                            "USC",
                            "USF",
                            "USM",
                            "USU",
                            "UTAH",
                            "UTEP",
                            "UTSA",
                            "UVA",
                            "VAN",
                            "VT",
                            "WAKE",
                            "WASH",
                            "WIS",
                            "WKU",
                            "WMU",
                            "WSU",
                            "WVU",
                            "WYO",
                        ],
                    },
                    {
                        league: "NCAAM_MM",
                        label: "March Madness",
                    },
                ],
            },
        },
    ],
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {
    module.exports = config;
}
